INSERT INTO datasource(datasource_id,data) values ('1','SHERLOCK HOLMES');
INSERT INTO datasource(datasource_id,data) values ('2','Sharma');
INSERT INTO datasource(datasource_id,data) values ('3','Kohli');
INSERT INTO datasource(datasource_id,data) values ('4','Rahane');
INSERT INTO datasource(datasource_id,data) values ('5','Yuvraj');
INSERT INTO datasource(datasource_id,data) values ('6','Raina');
INSERT INTO datasource(datasource_id,data) values ('7','Dhoni');
INSERT INTO datasource(datasource_id,data) values ('8','Pandya');
INSERT INTO datasource(datasource_id,data) values ('9','Nehra');
INSERT INTO datasource(datasource_id,data) values ('10','Jadeja');
INSERT INTO datasource(datasource_id,data) values ('11','Ashwin');